; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: bb8f2f358faeed56f5323e8766e7f4428f99eae248357e43ae4b648be743f3c2.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

define i16 @probe_cvt_rn_satfinite_relu_e4m3x2_bf16x2(i32 %packed) {
  %result = call i16 asm "cvt.rn.satfinite.relu.e4m3x2.bf16x2 $0, $1;", "=h,r"(i32 %packed)
  ret i16 %result
}
