; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 38b06acc5e57fe7d633cf36a7ab40bf43b50da7397dd87f0d4982f4f2645f311.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare float @llvm.nvvm.fma.rp.ftz.f(float, float, float)

define float @probe_fma_rp_ftz_f32(float %arg0, float %arg1, float %arg2) {
  %result = call float @llvm.nvvm.fma.rp.ftz.f(float %arg0, float %arg1, float %arg2)
  ret float %result
}
