; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 38b06acc5e57fe7d633cf36a7ab40bf43b50da7397dd87f0d4982f4f2645f311.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

define ptr addrspace(7) @probe_map_shared_rank(ptr %source_generic, i32 %rank) #0 {
  %source = addrspacecast ptr %source_generic to ptr addrspace(3)
  %mapped_integer = call i64 asm sideeffect "mapa.shared::cluster.u64 $0, $1, $2;", "=l,l,r"(ptr addrspace(3) %source, i32 %rank) #0
  %mapped = inttoptr i64 %mapped_integer to ptr addrspace(7)
  ret ptr addrspace(7) %mapped
}

attributes #0 = { convergent }
