; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 38b06acc5e57fe7d633cf36a7ab40bf43b50da7397dd87f0d4982f4f2645f311.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

define i32 @probe_max_ftz_nan_xorsign_abs_f16x2(i32 %a, i32 %b) {
  %result = call i32 asm "max.ftz.NaN.xorsign.abs.f16x2 $0, $1, $2;", "=r,r,r"(i32 %a, i32 %b)
  ret i32 %result
}
