; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: bb8f2f358faeed56f5323e8766e7f4428f99eae248357e43ae4b648be743f3c2.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

define i64 @probe_mbarrier_arrive_expect_tx_cluster(ptr %barrier_generic, i32 %bytes) #0 {
  %barrier = addrspacecast ptr %barrier_generic to ptr addrspace(3)
  %token = call i64 asm sideeffect "mbarrier.arrive.expect_tx.relaxed.cluster.shared::cta.b64 $0, [$1], $2;", "=l,l,r,~{memory}"(ptr addrspace(3) %barrier, i32 %bytes) #0
  ret i64 %token
}

attributes #0 = { convergent }
