; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: bb8f2f358faeed56f5323e8766e7f4428f99eae248357e43ae4b648be743f3c2.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

define void @probe_tensormap_replace_global_dim(ptr %tensor_map, i32 %new_value) {
  call void asm sideeffect "tensormap.replace.tile.global_dim.global.b1024.b32 [$0], $1, $2;", "l,n,r,~{memory}"(ptr %tensor_map, i32 0, i32 %new_value)
  ret void
}
