; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 38b06acc5e57fe7d633cf36a7ab40bf43b50da7397dd87f0d4982f4f2645f311.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare i32 @llvm.nvvm.read.ptx.sreg.lanemask.eq()

define i32 @probe_lanemask_eq() {
  %result = call i32 @llvm.nvvm.read.ptx.sreg.lanemask.eq()
  ret i32 %result
}

